from __future__ import annotations

import importlib.util
import unittest
from pathlib import Path

MODULE_PATH = Path(__file__).resolve().parents[1] / "scripts" / "render_delivery_graph.py"
SPEC = importlib.util.spec_from_file_location("render_delivery_graph", MODULE_PATH)
assert SPEC and SPEC.loader
render_delivery_graph = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(render_delivery_graph)


class DeliveryGraphRenderingTests(unittest.TestCase):
    def setUp(self) -> None:
        self.graph = {
            "schema_version": "delivery-graph/v1",
            "nodes": [
                {
                    "id": "stage-1",
                    "type": "stage",
                    "title": "Stage 1",
                    "summary": "Foundation",
                    "status": "completed",
                },
                {
                    "id": "problem-1",
                    "type": "problem",
                    "title": "Observed problem",
                    "summary": "Motivation",
                },
                {
                    "id": "stage-2",
                    "type": "stage",
                    "title": "Stage 2",
                    "summary": "Hardening",
                    "status": "completed",
                },
            ],
            "edges": [
                {"from": "stage-1", "to": "problem-1", "type": "revealed_problem"},
                {"from": "problem-1", "to": "stage-2", "type": "resolved_by"},
            ],
        }

    def test_render_is_stable(self) -> None:
        first = render_delivery_graph.render_graph(self.graph)
        second = render_delivery_graph.render_graph(self.graph)
        self.assertEqual(first, second)

    def test_render_contains_causal_chain(self) -> None:
        rendered = render_delivery_graph.render_graph(self.graph)
        self.assertIn('n_stage_1["Stage 1\\n(stage)"]', rendered)
        self.assertIn("n_stage_1 -->|revealed problem| n_problem_1", rendered)
        self.assertIn("n_problem_1 -->|resolved by| n_stage_2", rendered)

    def test_render_includes_generation_warning(self) -> None:
        rendered = render_delivery_graph.render_graph(self.graph)
        self.assertIn("Do not edit this file directly", rendered)
        self.assertTrue(rendered.endswith("\n"))


if __name__ == "__main__":
    unittest.main()
