#!/usr/bin/env python3
"""Render the compact IssueOps delivery graph as Mermaid Markdown."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


def load_graph(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as handle:
        data = json.load(handle)
    if not isinstance(data, dict):
        raise ValueError("delivery graph root must be an object")
    return data


def _mermaid_id(node_id: str) -> str:
    return "n_" + "".join(character if character.isalnum() else "_" for character in node_id)


def _escape_label(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', "'")


def render_graph(data: dict[str, Any]) -> str:
    lines = [
        "# IssueOps delivery graph",
        "",
        "Generated from `planning/delivery/delivery.yaml`. Do not edit this file directly.",
        "",
        "```mermaid",
        "flowchart LR",
    ]

    for node in data.get("nodes", []):
        node_id = _mermaid_id(str(node["id"]))
        title = _escape_label(str(node["title"]))
        node_type = _escape_label(str(node["type"]).replace("_", " "))
        lines.append(f'  {node_id}["{title}\\n({node_type})"]')

    lines.append("")
    for edge in data.get("edges", []):
        source = _mermaid_id(str(edge["from"]))
        target = _mermaid_id(str(edge["to"]))
        label = _escape_label(str(edge["type"]).replace("_", " "))
        lines.append(f"  {source} -->|{label}| {target}")

    lines.extend(["```", ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--graph",
        type=Path,
        default=Path("planning/delivery/delivery.yaml"),
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("planning/delivery/graph.md"),
    )
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    try:
        rendered = render_graph(load_graph(args.graph))
    except (OSError, ValueError, json.JSONDecodeError, KeyError) as exc:
        print(f"Delivery graph rendering failed: {exc}")
        return 1

    if args.check:
        try:
            existing = args.output.read_text(encoding="utf-8")
        except OSError as exc:
            print(f"Delivery graph freshness check failed: {exc}")
            return 1
        if existing != rendered:
            print("Delivery graph is stale. Run scripts/render_delivery_graph.py and commit graph.md.")
            return 1
        print("Delivery graph is current.")
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(rendered, encoding="utf-8")
    print(f"Rendered {args.output}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
